### PR TITLE
Allow for manifest path to be set as an env var `DBT_MANIFEST_PATH`

### PR DESCRIPTION
**Pull request by Lef-F**
This dbt autocompletion tool is a must have for dbt users and devs.
We use dbt in our airflow DAGs and thus have defined a custom path for the compilation results (`target/`) in `dbt_project.yml`.

This tiny PR adds support for the full path to the `manifest.json` to be specified as an environment variable `DBT_MANIFEST_PATH`. (+ some minor whitespace cleaning)

What do you think?

### CODE REVIEW

**Comment by b-per** [comment]
Thanks @Lef-F ! I will try it locally and merge it if all looks good!

**Review by b-per — CHANGES_REQUESTED** [review]
I tested it and it worked after fixing what I think is a typo.

Could you also do the same changes in `dbt-completion.bash` (with the exact same syntax), to make it work for both `bash` and `zsh`? 

I will get it merged after

**Comment by Lef-F** [comment]
Thanks for the feedback @b-per 🙏
Let me know what you think.

**Comment by b-per** [comment]
Thanks for the update @Lef-F ! I will try it again quickly today and will merge it after.

**Review by b-per — APPROVED** [review]

**Comment by b-per** [comment]
Thanks! I just merged it now.

**Pull request merged**
